---
platform: linux

resource_types:
- name: helm
  type: docker-image
  source:
    repository: tun31nn/helm-concourse-gcp
    tag: 2.12.2

resources:
- name: {{release_name}}
  type: helm
  source:
    release: {{release_name}}
    cluster_url: https://kubernetes
    cluster_ca: {{cluster_ca}}
    token: {{token}}
    repos:
    - name: gcs-repo
      url: gs://((bucket))

- name: app-image
  type: docker-image
  source:
    repository: gcr.io/((project))/app-image
    username: _json_key
    password: {{service_account_json}}

- name: app-source
  type: git
  source:
    uri: https://github.com/tun31nn/app-source.git
    branch: master
    username: {{git-user}}
    password: {{git-password}}

- name: chart-source
  type: git
  source:
    uri: https://github.com/tun31nn/chart-source.git
    branch: master
    username: {{git-user}}
    password: {{git-password}}


- name: hello-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/concourse-tutorial-hello-world

jobs:
  - name: build-image
    plan:
    - get: app-source
      trigger: true
    - task: get-version
      file: app-source/tasks/get-version.yaml
    - put: app-image
      params:
        build: app-source
        tag: app-version/version
        tag_as_latest: true

  - name: deploy-chart
    plan:
    - get: app-image
      trigger: true
      passed:
      - build-image
    - get: chart-source
      trigger: true
    - task: build-chart
      file: chart-source/tasks/prep-chart.yaml
      params:
        bucket: {{bucket}}
        chart_name: {{chart_name}}
    - put: {{release_name}}
      params:
        chart: gcs-repo/{{chart_name}}
        override_values:
        - key: image.repository
          path: app-image/repository
        - key: image.digest
          path: app-image/digest

  - name: Build and publish docker image
    plan:
    - get: app-source
      trigger: true
    - task: get-version
      file: app-source/tasks/get-version.yaml

    - put: hello-docker-image
      params:
        build: app-source
        tag: app-version/version
        tag_as_latest: true

